# ~/.tmux.conf
set -g default-terminal "xterm-256color"
set -g mouse on
# set -g status-style "fg=cyan,bg=black"

set -g escape-time 0
set -g base-index 1

bind -n M-h previous-window
bind -n M-l next-window

unbind C-b
set -g prefix C-space
bind C-space send-prefix

bind R source-file ~/.config/tmux/tmux.conf \; display-message "tmux-config RELOADED"

set-option -g status-justify "left"
#set-option utf8-default on
set-option -g mouse-select-pane
set-window-option -g mode-keys vi
#set-window-option -g utf8 on
# look'n feel
set -g status-position bottom
set-option -g history-limit 64096

set -sg escape-time 10

# allow the title bar to adapt to whatever host you connect to
set -g set-titles on
set -g set-titles-string "#T"

# Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'omerxx/tmux-sessionx'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'srcery-colors/srcery-tmux'

# plugin specific configuration
set -g @sessionx-custom-paths '$HOME/.config/'
set -g @continuum-restore 'on'
set -g @resurrect-strategy-nvim 'session'
set -g @srcery_tmux_patched_font '1'

run -b ~/.tmux/themes/srcery-tmux/srcery.tmux
run '~/.tmux/plugins/tpm/tpm'
